version: "3"
services: 
  db:
    container_name: java-api
    hostname: java-api
    image: mysql
    restart: always
    ports: 
      - 3306:3306
    environment:
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "Java"
      MYSQL_ROOT_PASSWORD: "admin"
    volumes: 
      - javaDB:/var/lib/mysql
volumes:
  javaDB: 